version: "3.9"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "12345"
      POSTGRES_USER: "bg"
      POSTGRES_DB: "autopark"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - "5432:5432"
    volumes:
      - ./db/migrations/:/docker-entrypoint-initdb.d
      - ../.:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bg -d autopark"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: always
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G
    networks:
      - postgres
  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - /path/to/local/data:/root/redis
      - /path/to/local/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_PASSWORD=12345
      - REDIS_PORT=6379
      - REDIS_DATABASES=16

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: "domnakolesaxxx@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "228"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - ./pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    restart: unless-stopped
    networks:
      - postgres

networks:
  postgres:
    driver: bridge
